import {
    ConfigProvider,
    Layout,
    Menu,
    Drawer,
    Tooltip,
    Tag,
    Divider,
    Button,
    Alert,
    Form,
    Input,
    Select,
    DatePicker,
    Checkbox,
    Popover,
    Tabs,
    TreeSelect,
    Card,
    Table,
    Spin,
    Anchor,
    Dropdown,
    Badge,
    Modal,
    Tree,
    Radio,
    Upload,
    Switch,
    InputNumber,
    Row,
    Col,
    RangePicker,
    TimePicker,
    TimeRangePicker,
    Transfer,
    Progress,
    Steps,
    Slider,
    Pagination,
    Empty,
    Collapse,
    notification
} from 'ant-design-vue';

export default function (app) {
    app.use(ConfigProvider);
    app.use(Layout);
    app.use(Menu);
    app.use(Drawer);
    app.use(Tooltip);
    app.use(Tag);
    app.use(Divider);
    app.use(Button);
    app.use(Alert);
    app.use(Form);
    app.use(Input);
    app.use(Select);
    app.use(DatePicker);
    app.use(Checkbox);
    app.use(Popover);
    app.use(Tabs);
    app.use(TreeSelect);
    app.use(Card);
    app.use(Table);
    app.use(Spin);
    app.use(Anchor);
    app.use(Dropdown);
    app.use(Badge);
    app.use(Modal);
    app.use(Tree)
    app.use(Radio)
    app.use(Upload)
    app.use(Switch)
    app.use(InputNumber)
    app.use(Row)
    app.use(Col)
    app.use(RangePicker)
    app.use(TimePicker)
    app.use(TimeRangePicker)
    app.use(Transfer)
    app.use(Progress)
    app.use(Steps)
    app.use(Slider)
    app.use(Pagination)
    app.use(Empty)
    app.use(Collapse)
    app.use(notification)
}
